name: ci
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build-linux:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: make lint test
